version: '3.9'

services:
  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: web_prod
    container_name: web_gunicorn_prod
    volumes:
      - static:/static
      - media:/media
    env_file:
      - ./.env
    depends_on:
      - pgdb
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - gunicorn

  pgdb:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - ./var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  
volumes:
  static:
  media: