version: '3.9'

services:
  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: web_prod
    container_name: web_gunicorn_prod
    command: gunicorn pitblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./pitblog:/pitblog
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - pgdb
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data/app/web/staticfiles
      - ./data/app/web/mediafiles
    ports:
      - "80:80"
    links:
      - gunicorn

  pgdb:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - ./var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
