# Generated by Django 4.1.3 on 2023-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_autor_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerto',
            field=models.TextField(verbose_name='Introdução'),
        ),
    ]
