# Generated by Django 4.1.3 on 2022-12-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='nome_comentario',
            field=models.CharField(max_length=150, verbose_name='NOME'),
        ),
    ]
